app:
  port: ':4000'
  cert_file: './cmd/api/certificate.pem'
  key_file: './cmd/api/key.pem'
  time_format: '2006-01-02T15:04:05'
  page_size: 10

#192.168.0.105
es:
  host: '192.168.0.105'
  port: '9200'
  cluster: superheromatch
  index: superhero
  batch_size: 50

cache:
  address: '192.168.0.105'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  suggestion_key_format: 'suggestion.%s'
  choice_key_format: 'choice.%s.%s'
  likes_key_format: 'likes.for.%s'

health:
  port: ':4080'
  shutdown_endpoint: '/api/v1/superhero_suggestions_health/shutdown'
  content_type: 'application/json'